- name: "Semaphore"
  hosts: centos
  vars_files:
    - 'vars/main.yml'
    - 'vars/secret.yml'
  roles:
    - role: geerlingguy.postgresql
      become: true
    - role: semaphore
      become: true
